/*
** RELEASE STATEMENT(s):
** 								UNLIMITED RIGHTS
** The Government has the right to use, modify, reproduce, release, perform,
** display, or disclose this application programmable interface in whole or in
** part, in any manner and for any purpose whatsoever, and to have or
** authorize others to do so.
**
** Statement A - Approved for public release; distribution is unlimited (29 July 2014).
*/

/*
** JTNC STANDARD SPECIFICATION:
** Modem Hardware Abstraction Layer API, Version: 3.0, 02 Oct 2013
** Mhal Gpp Api Extension
**
** API CATEGORY:
** JTNC Complex API
*/

/*
** MhalDevice.idl
*/

#ifndef __MHALDEVICE_DEFINED
#define __MHALDEVICE_DEFINED

#ifndef __JTRSCORBATYPES_DEFINED
#include <redhawk/JTRS/JtrsCorbaTypes.idl>
#endif

#ifndef __PACKET_DEFINED
#include <redhawk/PACKET/Packet.idl>
#endif

module MHAL {

	interface MHALPacketConsumer : Packet::PayloadStatus {
	
		void pushPacket (
			in unsigned short logicalDest,
			in JTRS::OctetSequence payload
		);
	};
	
	// Known MHAL Physical Destination Types
	typedef JTRS::ExtEnum MHALPhysicalDestination;
	const MHALPhysicalDestination MHALPhysicalDestination_NONE = 0;
	const MHALPhysicalDestination PHYSICAL_DESTINATION_DSP = 1;
	const MHALPhysicalDestination PHYSICAL_DESTINATION_FPGA = 2;
	const MHALPhysicalDestination PHYSICAL_DESTINATION_GPP = 3;
	
	interface PF_MHALPacketConsumer : MHALPacketConsumer {
		// Following type and consts are DEPRECATED 27-August-2009 - Use versions scoped to MHAL module!
		typedef MHAL::MHALPhysicalDestination MHALPhysicalDestination;
		const MHALPhysicalDestination MHALPhysicalDestination_NONE = 0;
		const MHALPhysicalDestination PHYSICAL_DESTINATION_DSP = 1;
		const MHALPhysicalDestination PHYSICAL_DESTINATION_FPGA = 2;
		const MHALPhysicalDestination PHYSICAL_DESTINATION_GPP = 3;
		
		void addTxRoute (
			in unsigned short logicalDest,
			in MHAL::MHALPhysicalDestination physicalDest
		);
	};
	
	interface WF_MHALPacketConsumer : MHALPacketConsumer {
		typedef sequence<unsigned short> RxRouteSequence;
		
		MHAL::WF_MHALPacketConsumer::RxRouteSequence getRxRoutes();
	};
	
};

#endif
