/*
** RELEASE STATEMENT(s):
** UNLIMITED RIGHTS
** The Government has the right to use, modify, reproduce, release, perform,
** display, or disclose this application programmable interface in whole or in
** part, in any manner and for any purpose whatsoever, and to have or
** authorize others to do so.
**
** Statement A - Approved for public release; distribution is unlimited (29 July 2014).
*/

/*
** JTNC STANDARD SPECIFICATION:
** Audio Port Device API, Version: 1.3.4, 29 July 2010
** Audio Sample Stream Extension
**
** API CATEGORY:
** JTNC Complex API
*/

/*
** AudioSampleStreamExt.idl - JTRS Audio Extension Service Set
*/
#ifndef __AUDIO_SAMPLE_STREAM_EXT_DEFINED
#define __AUDIO_SAMPLE_STREAM_EXT_DEFINED

#ifndef __PACKET_DEFINED
#include <redhawk/PACKET/Packet.idl>
#endif

#ifndef __DEVICEMESSAGECONTROL_DEFINED
#include <redhawk/DEVMSGCTL/DeviceMessageControl.idl>
#endif

module Audio
{
	// Packet Consumer
	interface SampleStream : Packet::UshortStream
	{
	};
	
	// Packet Provider Control
	interface SampleStreamControl : Packet::PayloadControl
	{
	};
	
	// Abort Messaging
	interface SampleMessageControl : DevMsgCtl::DeviceMessageControl
	{
	};
};
#endif //__AUDIO_SAMPLE_STREAM_EXT_DEFINED
