/*
** RELEASE STATEMENT(s):
** 							UNLIMITED RIGHTS
** The Government has the right to use, modify, reproduce, release, perform,
** display, or disclose this application programmable interface in whole or in
** part, in any manner and for any purpose whatsoever, and to have or
** authorize others to do so.
**
** Distribution Statement A - Approved for public release; distribution is
** unlimited (08 September 2015).
*/

/*
** JTNC STANDARD SPECIFICATION:
** Vocoder Service API, Version: 1.4, 26 February 2015
** G.729 Extension
**
** API CATEGORY:
** JTNC Complex API
*/

/*
** VocoderG729Ext.idl
*/

#ifndef __VOCODER_G729_EXT_DEFINED
#define __VOCODER_G729_EXT_DEFINED

#ifndef __VOCODER_DEFINED
#include <redhawk/VOCODER/Vocoder.idl>
#endif

module Vocoder
{
	const Algorithm ALG_G729 = 6;
	
	interface G729
	{
		struct Config
		{
			boolean enableVad; /* Voice Activity Detector */
		};
		
		void configureG729(in Config g729Cfg ) raises (JTRS::InvalidParameter);
		
		Config getG729Config();
		
	};
	
};
#endif //__VOCODER_G729_EXT_DEFINED
